# development docker image
# Base image. Can be FROM scratch but this excludes OS level dependencies.
# Official node base image: https://hub.docker.com/_/node
FROM node:18

# Set the working dir for application. Used for pulling from DAEMON
WORKDIR /app

# Install ffmpeg (depends on the OS). Everything on UNIX.
RUN apt-get update && apt-get install -y ffmpeg

# Copy the package.json and package-lock.json into working dir for dependencies
COPY package*.json ./

# Download the dependencies
RUN npm install
# Copy current app source into the docker image
COPY . .

# Make port 3001 available outside this container
EXPOSE 3001

# Set the command to be executed when running the container
CMD ["npm", "run", "dev"]






# production docker image